M48
; DRILL file {KiCad 8.0.5} date 2024-09-26T23:28:07-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-09-26T23:28:07-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X182.72Y-81.09
X182.72Y-86.87
T2
X128.7Y-61.5
X128.7Y-115.8
X183.896Y-61.468
X183.896Y-115.824
M30
